apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tux
  name: tux
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /tux
        name: empty-dir
    resources:
      limits:
        cpu: "0.5"
        memory: "100Mi"
      requests:
        cpu: "0.3"
        memory: "70Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: empty-dir
      emptyDir:
        sizeLimit: 256Mi
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc

