apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: webserver
spec:
  containers:
    - image: nginx
      name: girus
      volumeMounts:
        - mountPath: /tux
          name: primeiroemptydir
    - image: alpine
      name: alpine
      args:
        - sleep
        - "600"
      resources:
        limits:
          cpu: "0.8"
          memory: "80Mi"
        requests:
          cpu: "0.4"
          memory: "50Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: primeiroemptydir
      emptyDir:
        sizeLimit: 100Mi
