## Host Path
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  storageClassName: tux


## NFS

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: my-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.3.124
    path: /mnt/nfs
  storageClassName: tux
