apiVersion: monitoring.coreos.io/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  labels:
    app: nginx
spec: 
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - interval: 10s
      path: /metric
      targetPort: 9113

